// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: pkg/gateproto/login.proto

package gateproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LoginRequest is the client-to-Gate login payload. Field numbers use the
// expected legacy Gate protocol values; byte-level compatibility still needs
// verification against captured legacy fixtures. Authentication is deliberately
// outside this transport contract.
type LoginRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	LoginName        string                 `protobuf:"bytes,1,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	Token            string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	DeviceType       uint32                 `protobuf:"varint,3,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	AppVersion       string                 `protobuf:"bytes,4,opt,name=app_version,json=appVersion,proto3" json:"app_version,omitempty"`
	PhoneType        string                 `protobuf:"bytes,5,opt,name=phone_type,json=phoneType,proto3" json:"phone_type,omitempty"`
	PhoneName        string                 `protobuf:"bytes,6,opt,name=phone_name,json=phoneName,proto3" json:"phone_name,omitempty"`
	PhoneOs          string                 `protobuf:"bytes,7,opt,name=phone_os,json=phoneOs,proto3" json:"phone_os,omitempty"`
	Browser          string                 `protobuf:"bytes,8,opt,name=browser,proto3" json:"browser,omitempty"`
	NetType          string                 `protobuf:"bytes,9,opt,name=net_type,json=netType,proto3" json:"net_type,omitempty"`
	ScreenResolution string                 `protobuf:"bytes,10,opt,name=screen_resolution,json=screenResolution,proto3" json:"screen_resolution,omitempty"`
	WidthHeight      string                 `protobuf:"bytes,11,opt,name=width_height,json=widthHeight,proto3" json:"width_height,omitempty"`
	Language         string                 `protobuf:"bytes,12,opt,name=language,proto3" json:"language,omitempty"`
	// vid keeps the legacy C_LOGIN_REQ field name and wire number. Its business
	// meaning is intentionally not inferred by this transport-only contract.
	Vid           string `protobuf:"bytes,13,opt,name=vid,proto3" json:"vid,omitempty"`
	WebChannel    string `protobuf:"bytes,14,opt,name=web_channel,json=webChannel,proto3" json:"web_channel,omitempty"`
	WebSite       string `protobuf:"bytes,15,opt,name=web_site,json=webSite,proto3" json:"web_site,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_pkg_gateproto_login_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gateproto_login_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_gateproto_login_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetLoginName() string {
	if x != nil {
		return x.LoginName
	}
	return ""
}

func (x *LoginRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginRequest) GetDeviceType() uint32 {
	if x != nil {
		return x.DeviceType
	}
	return 0
}

func (x *LoginRequest) GetAppVersion() string {
	if x != nil {
		return x.AppVersion
	}
	return ""
}

func (x *LoginRequest) GetPhoneType() string {
	if x != nil {
		return x.PhoneType
	}
	return ""
}

func (x *LoginRequest) GetPhoneName() string {
	if x != nil {
		return x.PhoneName
	}
	return ""
}

func (x *LoginRequest) GetPhoneOs() string {
	if x != nil {
		return x.PhoneOs
	}
	return ""
}

func (x *LoginRequest) GetBrowser() string {
	if x != nil {
		return x.Browser
	}
	return ""
}

func (x *LoginRequest) GetNetType() string {
	if x != nil {
		return x.NetType
	}
	return ""
}

func (x *LoginRequest) GetScreenResolution() string {
	if x != nil {
		return x.ScreenResolution
	}
	return ""
}

func (x *LoginRequest) GetWidthHeight() string {
	if x != nil {
		return x.WidthHeight
	}
	return ""
}

func (x *LoginRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *LoginRequest) GetVid() string {
	if x != nil {
		return x.Vid
	}
	return ""
}

func (x *LoginRequest) GetWebChannel() string {
	if x != nil {
		return x.WebChannel
	}
	return ""
}

func (x *LoginRequest) GetWebSite() string {
	if x != nil {
		return x.WebSite
	}
	return ""
}

// LoginResponse is the Gate-to-client login result. Its field numbers use the
// expected legacy C_LOGIN_RSP values; byte-level compatibility still needs
// verification against captured legacy fixtures.
type LoginResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Code               uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	ServerTime         uint64                 `protobuf:"varint,2,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	UserFlag           uint32                 `protobuf:"varint,3,opt,name=user_flag,json=userFlag,proto3" json:"user_flag,omitempty"`
	Account            float64                `protobuf:"fixed64,4,opt,name=account,proto3" json:"account,omitempty"`
	Currency           string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Nickname           string                 `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Gender             uint32                 `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty"`
	Region             string                 `protobuf:"bytes,8,opt,name=region,proto3" json:"region,omitempty"`
	LastCustomerNumber string                 `protobuf:"bytes,9,opt,name=last_customer_number,json=lastCustomerNumber,proto3" json:"last_customer_number,omitempty"`
	Session            []byte                 `protobuf:"bytes,10,opt,name=session,proto3" json:"session,omitempty"`
	Confirm            uint32                 `protobuf:"varint,11,opt,name=confirm,proto3" json:"confirm,omitempty"`
	HeadIcon           string                 `protobuf:"bytes,12,opt,name=head_icon,json=headIcon,proto3" json:"head_icon,omitempty"`
	Vip                uint32                 `protobuf:"varint,13,opt,name=vip,proto3" json:"vip,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_pkg_gateproto_login_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gateproto_login_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_gateproto_login_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *LoginResponse) GetServerTime() uint64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

func (x *LoginResponse) GetUserFlag() uint32 {
	if x != nil {
		return x.UserFlag
	}
	return 0
}

func (x *LoginResponse) GetAccount() float64 {
	if x != nil {
		return x.Account
	}
	return 0
}

func (x *LoginResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *LoginResponse) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *LoginResponse) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *LoginResponse) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *LoginResponse) GetLastCustomerNumber() string {
	if x != nil {
		return x.LastCustomerNumber
	}
	return ""
}

func (x *LoginResponse) GetSession() []byte {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *LoginResponse) GetConfirm() uint32 {
	if x != nil {
		return x.Confirm
	}
	return 0
}

func (x *LoginResponse) GetHeadIcon() string {
	if x != nil {
		return x.HeadIcon
	}
	return ""
}

func (x *LoginResponse) GetVip() uint32 {
	if x != nil {
		return x.Vip
	}
	return 0
}

var File_pkg_gateproto_login_proto protoreflect.FileDescriptor

const file_pkg_gateproto_login_proto_rawDesc = "" +
	"\n" +
	"\x19pkg/gateproto/login.proto\x12\fgateproto.v1\"\xcd\x03\n" +
	"\fLoginRequest\x12\x1d\n" +
	"\n" +
	"login_name\x18\x01 \x01(\tR\tloginName\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1f\n" +
	"\vdevice_type\x18\x03 \x01(\rR\n" +
	"deviceType\x12\x1f\n" +
	"\vapp_version\x18\x04 \x01(\tR\n" +
	"appVersion\x12\x1d\n" +
	"\n" +
	"phone_type\x18\x05 \x01(\tR\tphoneType\x12\x1d\n" +
	"\n" +
	"phone_name\x18\x06 \x01(\tR\tphoneName\x12\x19\n" +
	"\bphone_os\x18\a \x01(\tR\aphoneOs\x12\x18\n" +
	"\abrowser\x18\b \x01(\tR\abrowser\x12\x19\n" +
	"\bnet_type\x18\t \x01(\tR\anetType\x12+\n" +
	"\x11screen_resolution\x18\n" +
	" \x01(\tR\x10screenResolution\x12!\n" +
	"\fwidth_height\x18\v \x01(\tR\vwidthHeight\x12\x1a\n" +
	"\blanguage\x18\f \x01(\tR\blanguage\x12\x10\n" +
	"\x03vid\x18\r \x01(\tR\x03vid\x12\x1f\n" +
	"\vweb_channel\x18\x0e \x01(\tR\n" +
	"webChannel\x12\x19\n" +
	"\bweb_site\x18\x0f \x01(\tR\awebSite\"\xf8\x02\n" +
	"\rLoginResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x1f\n" +
	"\vserver_time\x18\x02 \x01(\x04R\n" +
	"serverTime\x12\x1b\n" +
	"\tuser_flag\x18\x03 \x01(\rR\buserFlag\x12\x18\n" +
	"\aaccount\x18\x04 \x01(\x01R\aaccount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x1a\n" +
	"\bnickname\x18\x06 \x01(\tR\bnickname\x12\x16\n" +
	"\x06gender\x18\a \x01(\rR\x06gender\x12\x16\n" +
	"\x06region\x18\b \x01(\tR\x06region\x120\n" +
	"\x14last_customer_number\x18\t \x01(\tR\x12lastCustomerNumber\x12\x18\n" +
	"\asession\x18\n" +
	" \x01(\fR\asession\x12\x18\n" +
	"\aconfirm\x18\v \x01(\rR\aconfirm\x12\x1b\n" +
	"\thead_icon\x18\f \x01(\tR\bheadIcon\x12\x10\n" +
	"\x03vip\x18\r \x01(\rR\x03vipB8Z6github.com/NeoJay0705/gaming-core-casino/pkg/gateprotob\x06proto3"

var (
	file_pkg_gateproto_login_proto_rawDescOnce sync.Once
	file_pkg_gateproto_login_proto_rawDescData []byte
)

func file_pkg_gateproto_login_proto_rawDescGZIP() []byte {
	file_pkg_gateproto_login_proto_rawDescOnce.Do(func() {
		file_pkg_gateproto_login_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_gateproto_login_proto_rawDesc), len(file_pkg_gateproto_login_proto_rawDesc)))
	})
	return file_pkg_gateproto_login_proto_rawDescData
}

var file_pkg_gateproto_login_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_gateproto_login_proto_goTypes = []any{
	(*LoginRequest)(nil),  // 0: gateproto.v1.LoginRequest
	(*LoginResponse)(nil), // 1: gateproto.v1.LoginResponse
}
var file_pkg_gateproto_login_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_gateproto_login_proto_init() }
func file_pkg_gateproto_login_proto_init() {
	if File_pkg_gateproto_login_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_gateproto_login_proto_rawDesc), len(file_pkg_gateproto_login_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_gateproto_login_proto_goTypes,
		DependencyIndexes: file_pkg_gateproto_login_proto_depIdxs,
		MessageInfos:      file_pkg_gateproto_login_proto_msgTypes,
	}.Build()
	File_pkg_gateproto_login_proto = out.File
	file_pkg_gateproto_login_proto_goTypes = nil
	file_pkg_gateproto_login_proto_depIdxs = nil
}
