// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: examples/metrics/internal/protocol/broadcast.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BroadcastRoomCommand 是範例層的 room routing envelope。framework transport
// 只傳遞此 message 的 opaque bytes；client_payload 不在 Gate 解碼。
type BroadcastRoomCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomId          string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ClientCommandId uint32                 `protobuf:"varint,2,opt,name=client_command_id,json=clientCommandId,proto3" json:"client_command_id,omitempty"`
	ClientPayload   []byte                 `protobuf:"bytes,3,opt,name=client_payload,json=clientPayload,proto3" json:"client_payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BroadcastRoomCommand) Reset() {
	*x = BroadcastRoomCommand{}
	mi := &file_examples_metrics_internal_protocol_broadcast_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRoomCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRoomCommand) ProtoMessage() {}

func (x *BroadcastRoomCommand) ProtoReflect() protoreflect.Message {
	mi := &file_examples_metrics_internal_protocol_broadcast_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRoomCommand.ProtoReflect.Descriptor instead.
func (*BroadcastRoomCommand) Descriptor() ([]byte, []int) {
	return file_examples_metrics_internal_protocol_broadcast_proto_rawDescGZIP(), []int{0}
}

func (x *BroadcastRoomCommand) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *BroadcastRoomCommand) GetClientCommandId() uint32 {
	if x != nil {
		return x.ClientCommandId
	}
	return 0
}

func (x *BroadcastRoomCommand) GetClientPayload() []byte {
	if x != nil {
		return x.ClientPayload
	}
	return nil
}

var File_examples_metrics_internal_protocol_broadcast_proto protoreflect.FileDescriptor

const file_examples_metrics_internal_protocol_broadcast_proto_rawDesc = "" +
	"\n" +
	"2examples/metrics/internal/protocol/broadcast.proto\x12\x12metrics.example.v1\"\x82\x01\n" +
	"\x14BroadcastRoomCommand\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12*\n" +
	"\x11client_command_id\x18\x02 \x01(\rR\x0fclientCommandId\x12%\n" +
	"\x0eclient_payload\x18\x03 \x01(\fR\rclientPayloadBVZTgithub.com/NeoJay0705/gaming-core-casino/examples/metrics/internal/protocol;protocolb\x06proto3"

var (
	file_examples_metrics_internal_protocol_broadcast_proto_rawDescOnce sync.Once
	file_examples_metrics_internal_protocol_broadcast_proto_rawDescData []byte
)

func file_examples_metrics_internal_protocol_broadcast_proto_rawDescGZIP() []byte {
	file_examples_metrics_internal_protocol_broadcast_proto_rawDescOnce.Do(func() {
		file_examples_metrics_internal_protocol_broadcast_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_metrics_internal_protocol_broadcast_proto_rawDesc), len(file_examples_metrics_internal_protocol_broadcast_proto_rawDesc)))
	})
	return file_examples_metrics_internal_protocol_broadcast_proto_rawDescData
}

var file_examples_metrics_internal_protocol_broadcast_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_examples_metrics_internal_protocol_broadcast_proto_goTypes = []any{
	(*BroadcastRoomCommand)(nil), // 0: metrics.example.v1.BroadcastRoomCommand
}
var file_examples_metrics_internal_protocol_broadcast_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_metrics_internal_protocol_broadcast_proto_init() }
func file_examples_metrics_internal_protocol_broadcast_proto_init() {
	if File_examples_metrics_internal_protocol_broadcast_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_metrics_internal_protocol_broadcast_proto_rawDesc), len(file_examples_metrics_internal_protocol_broadcast_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_metrics_internal_protocol_broadcast_proto_goTypes,
		DependencyIndexes: file_examples_metrics_internal_protocol_broadcast_proto_depIdxs,
		MessageInfos:      file_examples_metrics_internal_protocol_broadcast_proto_msgTypes,
	}.Build()
	File_examples_metrics_internal_protocol_broadcast_proto = out.File
	file_examples_metrics_internal_protocol_broadcast_proto_goTypes = nil
	file_examples_metrics_internal_protocol_broadcast_proto_depIdxs = nil
}
