// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: examples/metrics/internal/protocol/push.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PushMode 是範例 server-send 壓測要驗證的 sender contract 模式。
type PushMode int32

const (
	PushMode_PUSH_MODE_UNSPECIFIED PushMode = 0
	PushMode_PUSH_MODE_BROADCAST   PushMode = 1
	PushMode_PUSH_MODE_PLAYER      PushMode = 2
)

// Enum value maps for PushMode.
var (
	PushMode_name = map[int32]string{
		0: "PUSH_MODE_UNSPECIFIED",
		1: "PUSH_MODE_BROADCAST",
		2: "PUSH_MODE_PLAYER",
	}
	PushMode_value = map[string]int32{
		"PUSH_MODE_UNSPECIFIED": 0,
		"PUSH_MODE_BROADCAST":   1,
		"PUSH_MODE_PLAYER":      2,
	}
)

func (x PushMode) Enum() *PushMode {
	p := new(PushMode)
	*p = x
	return p
}

func (x PushMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PushMode) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_metrics_internal_protocol_push_proto_enumTypes[0].Descriptor()
}

func (PushMode) Type() protoreflect.EnumType {
	return &file_examples_metrics_internal_protocol_push_proto_enumTypes[0]
}

func (x PushMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PushMode.Descriptor instead.
func (PushMode) EnumDescriptor() ([]byte, []int) {
	return file_examples_metrics_internal_protocol_push_proto_rawDescGZIP(), []int{0}
}

// StartPushRequest 是壓測控制訊息；只用於 examples/metrics，非 framework API。
type StartPushRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RunId          string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Mode           PushMode               `protobuf:"varint,2,opt,name=mode,proto3,enum=metrics.example.v1.PushMode" json:"mode,omitempty"`
	RoomId         string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	LoginNames     []string               `protobuf:"bytes,4,rep,name=login_names,json=loginNames,proto3" json:"login_names,omitempty"`
	IntervalMillis uint64                 `protobuf:"varint,5,opt,name=interval_millis,json=intervalMillis,proto3" json:"interval_millis,omitempty"`
	DurationMillis uint64                 `protobuf:"varint,6,opt,name=duration_millis,json=durationMillis,proto3" json:"duration_millis,omitempty"`
	PayloadBytes   uint32                 `protobuf:"varint,7,opt,name=payload_bytes,json=payloadBytes,proto3" json:"payload_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StartPushRequest) Reset() {
	*x = StartPushRequest{}
	mi := &file_examples_metrics_internal_protocol_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPushRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPushRequest) ProtoMessage() {}

func (x *StartPushRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_metrics_internal_protocol_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPushRequest.ProtoReflect.Descriptor instead.
func (*StartPushRequest) Descriptor() ([]byte, []int) {
	return file_examples_metrics_internal_protocol_push_proto_rawDescGZIP(), []int{0}
}

func (x *StartPushRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StartPushRequest) GetMode() PushMode {
	if x != nil {
		return x.Mode
	}
	return PushMode_PUSH_MODE_UNSPECIFIED
}

func (x *StartPushRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *StartPushRequest) GetLoginNames() []string {
	if x != nil {
		return x.LoginNames
	}
	return nil
}

func (x *StartPushRequest) GetIntervalMillis() uint64 {
	if x != nil {
		return x.IntervalMillis
	}
	return 0
}

func (x *StartPushRequest) GetDurationMillis() uint64 {
	if x != nil {
		return x.DurationMillis
	}
	return 0
}

func (x *StartPushRequest) GetPayloadBytes() uint32 {
	if x != nil {
		return x.PayloadBytes
	}
	return 0
}

// StartPushResponse 確認 Game 已接受 workload，並提供預期 tick 數供 load drain 驗證。
type StartPushResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	PlannedTicks  uint64                 `protobuf:"varint,2,opt,name=planned_ticks,json=plannedTicks,proto3" json:"planned_ticks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartPushResponse) Reset() {
	*x = StartPushResponse{}
	mi := &file_examples_metrics_internal_protocol_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartPushResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPushResponse) ProtoMessage() {}

func (x *StartPushResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_metrics_internal_protocol_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPushResponse.ProtoReflect.Descriptor instead.
func (*StartPushResponse) Descriptor() ([]byte, []int) {
	return file_examples_metrics_internal_protocol_push_proto_rawDescGZIP(), []int{1}
}

func (x *StartPushResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StartPushResponse) GetPlannedTicks() uint64 {
	if x != nil {
		return x.PlannedTicks
	}
	return 0
}

// PushMessage 是送往 client 的 opaque example payload。
type PushMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Sequence      uint64                 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	SentUnixNano  int64                  `protobuf:"varint,3,opt,name=sent_unix_nano,json=sentUnixNano,proto3" json:"sent_unix_nano,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessage) Reset() {
	*x = PushMessage{}
	mi := &file_examples_metrics_internal_protocol_push_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessage) ProtoMessage() {}

func (x *PushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_examples_metrics_internal_protocol_push_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessage.ProtoReflect.Descriptor instead.
func (*PushMessage) Descriptor() ([]byte, []int) {
	return file_examples_metrics_internal_protocol_push_proto_rawDescGZIP(), []int{2}
}

func (x *PushMessage) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *PushMessage) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PushMessage) GetSentUnixNano() int64 {
	if x != nil {
		return x.SentUnixNano
	}
	return 0
}

func (x *PushMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_examples_metrics_internal_protocol_push_proto protoreflect.FileDescriptor

const file_examples_metrics_internal_protocol_push_proto_rawDesc = "" +
	"\n" +
	"-examples/metrics/internal/protocol/push.proto\x12\x12metrics.example.v1\"\x8c\x02\n" +
	"\x10StartPushRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x120\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x1c.metrics.example.v1.PushModeR\x04mode\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x1f\n" +
	"\vlogin_names\x18\x04 \x03(\tR\n" +
	"loginNames\x12'\n" +
	"\x0finterval_millis\x18\x05 \x01(\x04R\x0eintervalMillis\x12'\n" +
	"\x0fduration_millis\x18\x06 \x01(\x04R\x0edurationMillis\x12#\n" +
	"\rpayload_bytes\x18\a \x01(\rR\fpayloadBytes\"O\n" +
	"\x11StartPushResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rplanned_ticks\x18\x02 \x01(\x04R\fplannedTicks\"\x80\x01\n" +
	"\vPushMessage\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x04R\bsequence\x12$\n" +
	"\x0esent_unix_nano\x18\x03 \x01(\x03R\fsentUnixNano\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload*T\n" +
	"\bPushMode\x12\x19\n" +
	"\x15PUSH_MODE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PUSH_MODE_BROADCAST\x10\x01\x12\x14\n" +
	"\x10PUSH_MODE_PLAYER\x10\x02BVZTgithub.com/NeoJay0705/gaming-core-casino/examples/metrics/internal/protocol;protocolb\x06proto3"

var (
	file_examples_metrics_internal_protocol_push_proto_rawDescOnce sync.Once
	file_examples_metrics_internal_protocol_push_proto_rawDescData []byte
)

func file_examples_metrics_internal_protocol_push_proto_rawDescGZIP() []byte {
	file_examples_metrics_internal_protocol_push_proto_rawDescOnce.Do(func() {
		file_examples_metrics_internal_protocol_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_metrics_internal_protocol_push_proto_rawDesc), len(file_examples_metrics_internal_protocol_push_proto_rawDesc)))
	})
	return file_examples_metrics_internal_protocol_push_proto_rawDescData
}

var file_examples_metrics_internal_protocol_push_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_examples_metrics_internal_protocol_push_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_examples_metrics_internal_protocol_push_proto_goTypes = []any{
	(PushMode)(0),             // 0: metrics.example.v1.PushMode
	(*StartPushRequest)(nil),  // 1: metrics.example.v1.StartPushRequest
	(*StartPushResponse)(nil), // 2: metrics.example.v1.StartPushResponse
	(*PushMessage)(nil),       // 3: metrics.example.v1.PushMessage
}
var file_examples_metrics_internal_protocol_push_proto_depIdxs = []int32{
	0, // 0: metrics.example.v1.StartPushRequest.mode:type_name -> metrics.example.v1.PushMode
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_examples_metrics_internal_protocol_push_proto_init() }
func file_examples_metrics_internal_protocol_push_proto_init() {
	if File_examples_metrics_internal_protocol_push_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_metrics_internal_protocol_push_proto_rawDesc), len(file_examples_metrics_internal_protocol_push_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_metrics_internal_protocol_push_proto_goTypes,
		DependencyIndexes: file_examples_metrics_internal_protocol_push_proto_depIdxs,
		EnumInfos:         file_examples_metrics_internal_protocol_push_proto_enumTypes,
		MessageInfos:      file_examples_metrics_internal_protocol_push_proto_msgTypes,
	}.Build()
	File_examples_metrics_internal_protocol_push_proto = out.File
	file_examples_metrics_internal_protocol_push_proto_goTypes = nil
	file_examples_metrics_internal_protocol_push_proto_depIdxs = nil
}
