// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: examples/metrics/internal/protocol/room.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnterRoomRequest 要求範例 Gate 將已登入連線移入 room_id。
type EnterRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterRoomRequest) Reset() {
	*x = EnterRoomRequest{}
	mi := &file_examples_metrics_internal_protocol_room_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterRoomRequest) ProtoMessage() {}

func (x *EnterRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_examples_metrics_internal_protocol_room_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterRoomRequest.ProtoReflect.Descriptor instead.
func (*EnterRoomRequest) Descriptor() ([]byte, []int) {
	return file_examples_metrics_internal_protocol_room_proto_rawDescGZIP(), []int{0}
}

func (x *EnterRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

// EnterRoomResponse 回報範例進房流程的處理結果。
type EnterRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterRoomResponse) Reset() {
	*x = EnterRoomResponse{}
	mi := &file_examples_metrics_internal_protocol_room_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterRoomResponse) ProtoMessage() {}

func (x *EnterRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_examples_metrics_internal_protocol_room_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterRoomResponse.ProtoReflect.Descriptor instead.
func (*EnterRoomResponse) Descriptor() ([]byte, []int) {
	return file_examples_metrics_internal_protocol_room_proto_rawDescGZIP(), []int{1}
}

func (x *EnterRoomResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

var File_examples_metrics_internal_protocol_room_proto protoreflect.FileDescriptor

const file_examples_metrics_internal_protocol_room_proto_rawDesc = "" +
	"\n" +
	"-examples/metrics/internal/protocol/room.proto\x12\x12metrics.example.v1\"+\n" +
	"\x10EnterRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\"'\n" +
	"\x11EnterRoomResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04codeBVZTgithub.com/NeoJay0705/gaming-core-casino/examples/metrics/internal/protocol;protocolb\x06proto3"

var (
	file_examples_metrics_internal_protocol_room_proto_rawDescOnce sync.Once
	file_examples_metrics_internal_protocol_room_proto_rawDescData []byte
)

func file_examples_metrics_internal_protocol_room_proto_rawDescGZIP() []byte {
	file_examples_metrics_internal_protocol_room_proto_rawDescOnce.Do(func() {
		file_examples_metrics_internal_protocol_room_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_examples_metrics_internal_protocol_room_proto_rawDesc), len(file_examples_metrics_internal_protocol_room_proto_rawDesc)))
	})
	return file_examples_metrics_internal_protocol_room_proto_rawDescData
}

var file_examples_metrics_internal_protocol_room_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_examples_metrics_internal_protocol_room_proto_goTypes = []any{
	(*EnterRoomRequest)(nil),  // 0: metrics.example.v1.EnterRoomRequest
	(*EnterRoomResponse)(nil), // 1: metrics.example.v1.EnterRoomResponse
}
var file_examples_metrics_internal_protocol_room_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_metrics_internal_protocol_room_proto_init() }
func file_examples_metrics_internal_protocol_room_proto_init() {
	if File_examples_metrics_internal_protocol_room_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_examples_metrics_internal_protocol_room_proto_rawDesc), len(file_examples_metrics_internal_protocol_room_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_metrics_internal_protocol_room_proto_goTypes,
		DependencyIndexes: file_examples_metrics_internal_protocol_room_proto_depIdxs,
		MessageInfos:      file_examples_metrics_internal_protocol_room_proto_msgTypes,
	}.Build()
	File_examples_metrics_internal_protocol_room_proto = out.File
	file_examples_metrics_internal_protocol_room_proto_goTypes = nil
	file_examples_metrics_internal_protocol_room_proto_depIdxs = nil
}
