// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: pkg/serversend/serversend.proto

package serversend

import (
	gatelink "github.com/NeoJay0705/gaming-core-casino/pkg/gatelink"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SendPlayersCommand is the framework-owned routing envelope for a batch
// player delivery command. client_payload remains opaque to this package's
// transport and is decoded only by the eventual client-facing product code.
type SendPlayersCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*PlayerDelivery      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendPlayersCommand) Reset() {
	*x = SendPlayersCommand{}
	mi := &file_pkg_serversend_serversend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendPlayersCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendPlayersCommand) ProtoMessage() {}

func (x *SendPlayersCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_serversend_serversend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendPlayersCommand.ProtoReflect.Descriptor instead.
func (*SendPlayersCommand) Descriptor() ([]byte, []int) {
	return file_pkg_serversend_serversend_proto_rawDescGZIP(), []int{0}
}

func (x *SendPlayersCommand) GetMessages() []*PlayerDelivery {
	if x != nil {
		return x.Messages
	}
	return nil
}

type PlayerDelivery struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LoginName       string                 `protobuf:"bytes,1,opt,name=login_name,json=loginName,proto3" json:"login_name,omitempty"`
	ClientCommandId uint32                 `protobuf:"varint,2,opt,name=client_command_id,json=clientCommandId,proto3" json:"client_command_id,omitempty"`
	ClientPayload   []byte                 `protobuf:"bytes,3,opt,name=client_payload,json=clientPayload,proto3" json:"client_payload,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PlayerDelivery) Reset() {
	*x = PlayerDelivery{}
	mi := &file_pkg_serversend_serversend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerDelivery) ProtoMessage() {}

func (x *PlayerDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_serversend_serversend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerDelivery.ProtoReflect.Descriptor instead.
func (*PlayerDelivery) Descriptor() ([]byte, []int) {
	return file_pkg_serversend_serversend_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerDelivery) GetLoginName() string {
	if x != nil {
		return x.LoginName
	}
	return ""
}

func (x *PlayerDelivery) GetClientCommandId() uint32 {
	if x != nil {
		return x.ClientCommandId
	}
	return 0
}

func (x *PlayerDelivery) GetClientPayload() []byte {
	if x != nil {
		return x.ClientPayload
	}
	return nil
}

var File_pkg_serversend_serversend_proto protoreflect.FileDescriptor

const file_pkg_serversend_serversend_proto_rawDesc = "" +
	"\n" +
	"\x1fpkg/serversend/serversend.proto\x12\rserversend.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1bpkg/gatelink/gatelink.proto\"O\n" +
	"\x12SendPlayersCommand\x129\n" +
	"\bmessages\x18\x01 \x03(\v2\x1d.serversend.v1.PlayerDeliveryR\bmessages\"\x82\x01\n" +
	"\x0ePlayerDelivery\x12\x1d\n" +
	"\n" +
	"login_name\x18\x01 \x01(\tR\tloginName\x12*\n" +
	"\x11client_command_id\x18\x02 \x01(\rR\x0fclientCommandId\x12%\n" +
	"\x0eclient_payload\x18\x03 \x01(\fR\rclientPayload2K\n" +
	"\fGateDelivery\x12;\n" +
	"\aForward\x12\x18.gatelink.v1.GateRequest\x1a\x16.google.protobuf.EmptyB9Z7github.com/NeoJay0705/gaming-core-casino/pkg/serversendb\x06proto3"

var (
	file_pkg_serversend_serversend_proto_rawDescOnce sync.Once
	file_pkg_serversend_serversend_proto_rawDescData []byte
)

func file_pkg_serversend_serversend_proto_rawDescGZIP() []byte {
	file_pkg_serversend_serversend_proto_rawDescOnce.Do(func() {
		file_pkg_serversend_serversend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_serversend_serversend_proto_rawDesc), len(file_pkg_serversend_serversend_proto_rawDesc)))
	})
	return file_pkg_serversend_serversend_proto_rawDescData
}

var file_pkg_serversend_serversend_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_serversend_serversend_proto_goTypes = []any{
	(*SendPlayersCommand)(nil),   // 0: serversend.v1.SendPlayersCommand
	(*PlayerDelivery)(nil),       // 1: serversend.v1.PlayerDelivery
	(*gatelink.GateRequest)(nil), // 2: gatelink.v1.GateRequest
	(*emptypb.Empty)(nil),        // 3: google.protobuf.Empty
}
var file_pkg_serversend_serversend_proto_depIdxs = []int32{
	1, // 0: serversend.v1.SendPlayersCommand.messages:type_name -> serversend.v1.PlayerDelivery
	2, // 1: serversend.v1.GateDelivery.Forward:input_type -> gatelink.v1.GateRequest
	3, // 2: serversend.v1.GateDelivery.Forward:output_type -> google.protobuf.Empty
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_serversend_serversend_proto_init() }
func file_pkg_serversend_serversend_proto_init() {
	if File_pkg_serversend_serversend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_serversend_serversend_proto_rawDesc), len(file_pkg_serversend_serversend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_serversend_serversend_proto_goTypes,
		DependencyIndexes: file_pkg_serversend_serversend_proto_depIdxs,
		MessageInfos:      file_pkg_serversend_serversend_proto_msgTypes,
	}.Build()
	File_pkg_serversend_serversend_proto = out.File
	file_pkg_serversend_serversend_proto_goTypes = nil
	file_pkg_serversend_serversend_proto_depIdxs = nil
}
