// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: pkg/serversend/serversend.proto

package serversend

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GateDelivery_SendToConnection_FullMethodName = "/serversend.v1.GateDelivery/SendToConnection"
	GateDelivery_SendToPlayer_FullMethodName     = "/serversend.v1.GateDelivery/SendToPlayer"
	GateDelivery_BroadcastRoom_FullMethodName    = "/serversend.v1.GateDelivery/BroadcastRoom"
)

// GateDeliveryClient is the client API for GateDelivery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GateDelivery receives Game-originated client messages at one Gate instance.
// A caller that wants fan-out invokes the same unary method once per endpoint;
// a normal gRPC round-robin target alone is not a broadcast primitive.
type GateDeliveryClient interface {
	SendToConnection(ctx context.Context, in *SendToConnectionRequest, opts ...grpc.CallOption) (*DeliveryResponse, error)
	SendToPlayer(ctx context.Context, in *SendToPlayerRequest, opts ...grpc.CallOption) (*DeliveryResponse, error)
	BroadcastRoom(ctx context.Context, in *BroadcastRoomRequest, opts ...grpc.CallOption) (*DeliveryResponse, error)
}

type gateDeliveryClient struct {
	cc grpc.ClientConnInterface
}

func NewGateDeliveryClient(cc grpc.ClientConnInterface) GateDeliveryClient {
	return &gateDeliveryClient{cc}
}

func (c *gateDeliveryClient) SendToConnection(ctx context.Context, in *SendToConnectionRequest, opts ...grpc.CallOption) (*DeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryResponse)
	err := c.cc.Invoke(ctx, GateDelivery_SendToConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateDeliveryClient) SendToPlayer(ctx context.Context, in *SendToPlayerRequest, opts ...grpc.CallOption) (*DeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryResponse)
	err := c.cc.Invoke(ctx, GateDelivery_SendToPlayer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gateDeliveryClient) BroadcastRoom(ctx context.Context, in *BroadcastRoomRequest, opts ...grpc.CallOption) (*DeliveryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryResponse)
	err := c.cc.Invoke(ctx, GateDelivery_BroadcastRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GateDeliveryServer is the server API for GateDelivery service.
// All implementations must embed UnimplementedGateDeliveryServer
// for forward compatibility.
//
// GateDelivery receives Game-originated client messages at one Gate instance.
// A caller that wants fan-out invokes the same unary method once per endpoint;
// a normal gRPC round-robin target alone is not a broadcast primitive.
type GateDeliveryServer interface {
	SendToConnection(context.Context, *SendToConnectionRequest) (*DeliveryResponse, error)
	SendToPlayer(context.Context, *SendToPlayerRequest) (*DeliveryResponse, error)
	BroadcastRoom(context.Context, *BroadcastRoomRequest) (*DeliveryResponse, error)
	mustEmbedUnimplementedGateDeliveryServer()
}

// UnimplementedGateDeliveryServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGateDeliveryServer struct{}

func (UnimplementedGateDeliveryServer) SendToConnection(context.Context, *SendToConnectionRequest) (*DeliveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendToConnection not implemented")
}
func (UnimplementedGateDeliveryServer) SendToPlayer(context.Context, *SendToPlayerRequest) (*DeliveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendToPlayer not implemented")
}
func (UnimplementedGateDeliveryServer) BroadcastRoom(context.Context, *BroadcastRoomRequest) (*DeliveryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BroadcastRoom not implemented")
}
func (UnimplementedGateDeliveryServer) mustEmbedUnimplementedGateDeliveryServer() {}
func (UnimplementedGateDeliveryServer) testEmbeddedByValue()                      {}

// UnsafeGateDeliveryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GateDeliveryServer will
// result in compilation errors.
type UnsafeGateDeliveryServer interface {
	mustEmbedUnimplementedGateDeliveryServer()
}

func RegisterGateDeliveryServer(s grpc.ServiceRegistrar, srv GateDeliveryServer) {
	// If the following call panics, it indicates UnimplementedGateDeliveryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GateDelivery_ServiceDesc, srv)
}

func _GateDelivery_SendToConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateDeliveryServer).SendToConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateDelivery_SendToConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateDeliveryServer).SendToConnection(ctx, req.(*SendToConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateDelivery_SendToPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendToPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateDeliveryServer).SendToPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateDelivery_SendToPlayer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateDeliveryServer).SendToPlayer(ctx, req.(*SendToPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GateDelivery_BroadcastRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateDeliveryServer).BroadcastRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateDelivery_BroadcastRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateDeliveryServer).BroadcastRoom(ctx, req.(*BroadcastRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GateDelivery_ServiceDesc is the grpc.ServiceDesc for GateDelivery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GateDelivery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "serversend.v1.GateDelivery",
	HandlerType: (*GateDeliveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendToConnection",
			Handler:    _GateDelivery_SendToConnection_Handler,
		},
		{
			MethodName: "SendToPlayer",
			Handler:    _GateDelivery_SendToPlayer_Handler,
		},
		{
			MethodName: "BroadcastRoom",
			Handler:    _GateDelivery_BroadcastRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/serversend/serversend.proto",
}
