// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: pkg/gatelink/gatelink.proto

package gatelink

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GateRequestService_Forward_FullMethodName = "/gatelink.v1.GateRequestService/Forward"
)

// GateRequestServiceClient is the client API for GateRequestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// GateRequestService is the direct Gate-to-Game ingress contract.
type GateRequestServiceClient interface {
	Forward(ctx context.Context, in *GateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type gateRequestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGateRequestServiceClient(cc grpc.ClientConnInterface) GateRequestServiceClient {
	return &gateRequestServiceClient{cc}
}

func (c *gateRequestServiceClient) Forward(ctx context.Context, in *GateRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, GateRequestService_Forward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GateRequestServiceServer is the server API for GateRequestService service.
// All implementations must embed UnimplementedGateRequestServiceServer
// for forward compatibility.
//
// GateRequestService is the direct Gate-to-Game ingress contract.
type GateRequestServiceServer interface {
	Forward(context.Context, *GateRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedGateRequestServiceServer()
}

// UnimplementedGateRequestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGateRequestServiceServer struct{}

func (UnimplementedGateRequestServiceServer) Forward(context.Context, *GateRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedGateRequestServiceServer) mustEmbedUnimplementedGateRequestServiceServer() {}
func (UnimplementedGateRequestServiceServer) testEmbeddedByValue()                            {}

// UnsafeGateRequestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GateRequestServiceServer will
// result in compilation errors.
type UnsafeGateRequestServiceServer interface {
	mustEmbedUnimplementedGateRequestServiceServer()
}

func RegisterGateRequestServiceServer(s grpc.ServiceRegistrar, srv GateRequestServiceServer) {
	// If the following call panics, it indicates UnimplementedGateRequestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GateRequestService_ServiceDesc, srv)
}

func _GateRequestService_Forward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GateRequestServiceServer).Forward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GateRequestService_Forward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GateRequestServiceServer).Forward(ctx, req.(*GateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GateRequestService_ServiceDesc is the grpc.ServiceDesc for GateRequestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GateRequestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gatelink.v1.GateRequestService",
	HandlerType: (*GateRequestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Forward",
			Handler:    _GateRequestService_Forward_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/gatelink/gatelink.proto",
}
