// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: pkg/gatelink/gatelink.proto

package gatelink

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GateRequest keeps the player packet opaque. The Game product owns decoding
// and dispatching when its business module is added.
type GateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     uint32                 `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateRequest) Reset() {
	*x = GateRequest{}
	mi := &file_pkg_gatelink_gatelink_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateRequest) ProtoMessage() {}

func (x *GateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gatelink_gatelink_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateRequest.ProtoReflect.Descriptor instead.
func (*GateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_gatelink_gatelink_proto_rawDescGZIP(), []int{0}
}

func (x *GateRequest) GetCommandId() uint32 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *GateRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_pkg_gatelink_gatelink_proto protoreflect.FileDescriptor

const file_pkg_gatelink_gatelink_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/gatelink/gatelink.proto\x12\vgatelink.v1\x1a\x1bgoogle/protobuf/empty.proto\"F\n" +
	"\vGateRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\rR\tcommandId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload2Q\n" +
	"\x12GateRequestService\x12;\n" +
	"\aForward\x12\x18.gatelink.v1.GateRequest\x1a\x16.google.protobuf.EmptyB7Z5github.com/NeoJay0705/gaming-core-casino/pkg/gatelinkb\x06proto3"

var (
	file_pkg_gatelink_gatelink_proto_rawDescOnce sync.Once
	file_pkg_gatelink_gatelink_proto_rawDescData []byte
)

func file_pkg_gatelink_gatelink_proto_rawDescGZIP() []byte {
	file_pkg_gatelink_gatelink_proto_rawDescOnce.Do(func() {
		file_pkg_gatelink_gatelink_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_gatelink_gatelink_proto_rawDesc), len(file_pkg_gatelink_gatelink_proto_rawDesc)))
	})
	return file_pkg_gatelink_gatelink_proto_rawDescData
}

var file_pkg_gatelink_gatelink_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_gatelink_gatelink_proto_goTypes = []any{
	(*GateRequest)(nil),   // 0: gatelink.v1.GateRequest
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_pkg_gatelink_gatelink_proto_depIdxs = []int32{
	0, // 0: gatelink.v1.GateRequestService.Forward:input_type -> gatelink.v1.GateRequest
	1, // 1: gatelink.v1.GateRequestService.Forward:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_gatelink_gatelink_proto_init() }
func file_pkg_gatelink_gatelink_proto_init() {
	if File_pkg_gatelink_gatelink_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_gatelink_gatelink_proto_rawDesc), len(file_pkg_gatelink_gatelink_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_gatelink_gatelink_proto_goTypes,
		DependencyIndexes: file_pkg_gatelink_gatelink_proto_depIdxs,
		MessageInfos:      file_pkg_gatelink_gatelink_proto_msgTypes,
	}.Build()
	File_pkg_gatelink_gatelink_proto = out.File
	file_pkg_gatelink_gatelink_proto_goTypes = nil
	file_pkg_gatelink_gatelink_proto_depIdxs = nil
}
